version: '3.8'

services:
  text-generation-inference:
    image: ghcr.io/huggingface/text-generation-inference:1.4-rocm
    ports:
      - "8082:80"
    volumes:
      - "/data:/data"
    devices:
      - "/dev/kfd:/dev/kfd"
      - "/dev/dri:/dev/dri"
    shm_size: 1g
    environment:
      - HUGGING_FACE_HUB_TOKEN=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
    command: "--model-id meta-llama/Llama-2-7b-chat-hf"
