wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.4
    framework: huggingface
    huggingface_version: 4.38.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1710865444.0
    t:
      1:
      - 11
      - 30
      - 49
      - 55
      - 86
      - 93
      - 105
      3:
      - 23
      4: 3.10.12
      5: 0.16.4
      6: 4.38.2
      8:
      - 5
      13: linux-x86_64
