#----------------------- Admin Credentials
admin_username: admin
admin_password: admin
#----------------------- Hugging Configuration
Hugging_ACCESS_TOKEN : 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
#----------------------- Weight and Biases Key 
WANDB_KEY : 0e7a7b13e06cf5b342134be31eba89e3279dec96
WANDB_ENABLE : True
#----------------------- Database Configuration
SECRET_KEY: 09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7 # Database secret Key
ALGORITHM: HS256
ACCESS_TOKEN_EXPIRE_MINUTES: 3000
DB_SERVICE_URL : http://localhost:8088
DB_DIR: CURRENT_DIR
Ray_service_URL : "http://localhost:8000"
API_service_URL : "http://localhost:8081"
DB_name: chat_bot_db
#----------------------- API Port
API_port: 8083
#----------------------- Vector Database Cluster Configuration
VD_WeaviateEmbedder_num_gpus: 0.1
VD_deployment_num_gpus: 0.1
VD_min_replicas: 1
VD_initial_replicas: 1
VD_max_replicas: 2
VD_target_num_ongoing_requests_per_replica: 2
VD_max_concurrent_queries: 2
VD_graceful_shutdown_wait_loop_s: 15
weaviate_client_url : "http://localhost:8080"
VD_number_actors : 3
VD_chunk_size : 1000
VD_chunk_overlap : 100
max_file_size : 10 # in MB
#----------------------- LLM Configuration
max_batch_size : 2
batch_wait_timeout_s: 0.1
#------------------- Kubernetes Cluster 
cluster_URL:  http://192.168.199.207:8265

#------------------- LLM Models

Langchain_access_key: ls__c832be79a7804c9cb85244aff1782f6e
LLMs: 
  - name: Llama_7b
    url: "http://localhost:8082/" 
    model_id: "meta-llama/Llama-2-13b-chat-hf"
    temperature: 0.01
    max_new_tokens: 512
    repetition_penalty: 1.1
    batch_size: 2
    top_k: 10
    top_p: 0.95
    typical_p: 0.95
    repetition_penalty: 1.03
    route_prefix: Llama_13b
    streaming: True
   